spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app-sell
    username: root
    password: uu.qoEW)w2a9147

  jpa:
    hibernate:
      ##?????????? sql ???
      ddl-auto: update
    show-sql: true