spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app-sell
    username: root
    password: ${DB_PASSWORD}
  freemarker:
    expose-request-attributes: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false